-- Users table (quoted because "user" is a reserved word in PostgreSQL)
CREATE TABLE "users" (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    display_name   VARCHAR(255),
    email          VARCHAR(255) UNIQUE,
    password_hash  VARCHAR(255),
    gender         VARCHAR(255),
    age_group      VARCHAR(255),
    region         VARCHAR(255),
    ethnicity      VARCHAR(255),
    elo_rating     INTEGER NOT NULL DEFAULT 1000,
    streak         INTEGER NOT NULL DEFAULT 0,
    created_at     TIMESTAMP
);

-- Topics table
CREATE TABLE topics (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    question    VARCHAR(255) NOT NULL,
    category    VARCHAR(255),
    options     JSONB,
    active_date DATE,
    status      VARCHAR(255),
    created_at  TIMESTAMP
);

-- Votes table
CREATE TABLE votes (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    BIGINT,
    topic_id   BIGINT,
    rankings   JSONB,
    created_at TIMESTAMP,
    CONSTRAINT uk_votes_user_topic UNIQUE (user_id, topic_id)
);

-- Elo history table
CREATE TABLE elo_history (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id          BIGINT,
    topic_id         BIGINT,
    previous_elo     INTEGER NOT NULL,
    new_elo          INTEGER NOT NULL,
    similarity_score DOUBLE PRECISION NOT NULL,
    created_at       TIMESTAMP
);

-- Topic suggestions table
CREATE TABLE topic_suggestions (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    BIGINT,
    question   VARCHAR(255) NOT NULL,
    category   VARCHAR(255),
    options    JSONB,
    status     VARCHAR(255),
    upvotes    INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMP
);

-- Suggestion upvotes table
CREATE TABLE suggestion_upvotes (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id       BIGINT,
    suggestion_id BIGINT,
    created_at    TIMESTAMP,
    CONSTRAINT uk_suggestion_upvotes_user_suggestion UNIQUE (user_id, suggestion_id)
);

-- Performance indexes
CREATE INDEX idx_topics_status ON topics (status);
CREATE INDEX idx_votes_user_id ON votes (user_id);
CREATE INDEX idx_votes_topic_id ON votes (topic_id);
CREATE INDEX idx_elo_history_user_id ON elo_history (user_id);
CREATE INDEX idx_elo_history_topic_id ON elo_history (topic_id);
CREATE INDEX idx_topic_suggestions_user_id ON topic_suggestions (user_id);
CREATE INDEX idx_topic_suggestions_status ON topic_suggestions (status);
CREATE INDEX idx_suggestion_upvotes_user_id ON suggestion_upvotes (user_id);
CREATE INDEX idx_suggestion_upvotes_suggestion_id ON suggestion_upvotes (suggestion_id);
